"""Add mood and emotion tracking to Session model

Revision ID: a1b2c3d4e5f6
Revises: xxxxxxxx_initial_setup_placeholder # Placeholder for the revision that created the 'sessions' table
Create Date: 2024-03-11 10:00:00.000000 # Example timestamp

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'xxxxxxxx_initial_setup_placeholder' # Replace with actual previous migration ID
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood_before', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mood_after', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emotions_before', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('emotions_after', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('emotions_after')
        batch_op.drop_column('emotions_before')
        batch_op.drop_column('mood_after')
        batch_op.drop_column('mood_before')

    # ### end Alembic commands ###
